import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { X, CheckCircle, XCircle, ArrowRight } from 'lucide-react';

/**
 * QuizModal - Interactive quiz generated from uploaded content
 * 
 * Quiz questions are generated by the AI based on extracted content.
 * Supports multiple-choice and written-answer questions.
 * Auto-marks answers and provides immediate feedback.
 * Returns performance data for StudentProgress updates.
 */
export default function QuizModal({ questions, onClose, onComplete }) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState('');
  const [writtenAnswer, setWrittenAnswer] = useState('');
  const [showFeedback, setShowFeedback] = useState(false);
  const [isCorrect, setIsCorrect] = useState(false);
  const [results, setResults] = useState([]);

  const currentQuestion = questions[currentIndex];
  const isMultipleChoice = currentQuestion.type === 'multiple_choice';

  /**
   * Check if the answer is correct
   * For written answers, we do case-insensitive partial matching
   */
  const checkAnswer = () => {
    let correct = false;
    const userAnswer = isMultipleChoice ? selectedAnswer : writtenAnswer.trim().toLowerCase();
    
    if (isMultipleChoice) {
      correct = userAnswer === currentQuestion.correct_answer;
    } else {
      // For written answers, check if the answer contains key terms
      const correctAnswers = Array.isArray(currentQuestion.correct_answer) 
        ? currentQuestion.correct_answer 
        : [currentQuestion.correct_answer];
      correct = correctAnswers.some(ans => 
        userAnswer.includes(ans.toLowerCase()) || ans.toLowerCase().includes(userAnswer)
      );
    }

    setIsCorrect(correct);
    setShowFeedback(true);
    
    // Record result for this question
    setResults(prev => [...prev, {
      question: currentQuestion.question,
      skill: currentQuestion.skill || 'general',
      correct,
      userAnswer: isMultipleChoice ? selectedAnswer : writtenAnswer
    }]);
  };

  const handleNext = () => {
    setShowFeedback(false);
    setSelectedAnswer('');
    setWrittenAnswer('');
    
    if (currentIndex < questions.length - 1) {
      setCurrentIndex(currentIndex + 1);
    } else {
      // Quiz complete - return results
      const correctCount = results.filter(r => r.correct).length + (isCorrect ? 1 : 0);
      onComplete({
        total: questions.length,
        correct: correctCount,
        percentage: Math.round((correctCount / questions.length) * 100),
        results: [...results, {
          question: currentQuestion.question,
          skill: currentQuestion.skill || 'general',
          correct: isCorrect,
          userAnswer: isMultipleChoice ? selectedAnswer : writtenAnswer
        }]
      });
    }
  };

  return (
    <div 
      className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
      onClick={onClose}
    >
      <div 
        className="bg-white rounded-2xl max-w-lg w-full p-6 relative max-h-[90vh] overflow-y-auto"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold text-slate-800">
            Quiz ({currentIndex + 1}/{questions.length})
          </h3>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <X className="w-5 h-5" />
          </Button>
        </div>

        {/* Progress bar */}
        <div className="w-full h-2 bg-slate-100 rounded-full mb-6">
          <div 
            className="h-full bg-indigo-500 rounded-full transition-all"
            style={{ width: `${((currentIndex + 1) / questions.length) * 100}%` }}
          />
        </div>

        {/* Question */}
        <div className="mb-6">
          <p className="text-lg font-medium text-slate-800 mb-4">
            {currentQuestion.question}
          </p>

          {/* Multiple Choice Options */}
          {isMultipleChoice && (
            <div className="space-y-2">
              {currentQuestion.options.map((option, idx) => (
                <button
                  key={idx}
                  onClick={() => !showFeedback && setSelectedAnswer(option.id || option)}
                  disabled={showFeedback}
                  className={`w-full p-4 rounded-xl border-2 text-left transition-colors ${
                    showFeedback
                      ? (option.id || option) === currentQuestion.correct_answer
                        ? 'border-green-500 bg-green-50'
                        : (option.id || option) === selectedAnswer
                          ? 'border-red-500 bg-red-50'
                          : 'border-slate-200'
                      : selectedAnswer === (option.id || option)
                        ? 'border-indigo-500 bg-indigo-50'
                        : 'border-slate-200 hover:border-slate-300'
                  }`}
                >
                  <span className="font-medium">{option.text || option}</span>
                </button>
              ))}
            </div>
          )}

          {/* Written Answer */}
          {!isMultipleChoice && (
            <Input
              placeholder="Type your answer..."
              value={writtenAnswer}
              onChange={(e) => setWrittenAnswer(e.target.value)}
              disabled={showFeedback}
              className="text-lg"
            />
          )}
        </div>

        {/* Feedback */}
        {showFeedback && (
          <div className={`p-4 rounded-xl mb-6 ${isCorrect ? 'bg-green-50' : 'bg-red-50'}`}>
            <div className="flex items-center gap-2 mb-2">
              {isCorrect ? (
                <CheckCircle className="w-5 h-5 text-green-600" />
              ) : (
                <XCircle className="w-5 h-5 text-red-600" />
              )}
              <span className={`font-medium ${isCorrect ? 'text-green-700' : 'text-red-700'}`}>
                {isCorrect ? 'Correct!' : 'Not quite right'}
              </span>
            </div>
            {!isCorrect && currentQuestion.explanation && (
              <p className="text-sm text-slate-600">{currentQuestion.explanation}</p>
            )}
            {!isCorrect && (
              <p className="text-sm text-slate-600 mt-1">
                The correct answer is: <strong>{currentQuestion.correct_answer}</strong>
              </p>
            )}
          </div>
        )}

        {/* Actions */}
        <div className="flex justify-end gap-3">
          {!showFeedback ? (
            <Button 
              onClick={checkAnswer}
              disabled={isMultipleChoice ? !selectedAnswer : !writtenAnswer.trim()}
              className="bg-indigo-500 hover:bg-indigo-600"
            >
              Check Answer
            </Button>
          ) : (
            <Button 
              onClick={handleNext}
              className="bg-indigo-500 hover:bg-indigo-600"
            >
              {currentIndex === questions.length - 1 ? 'See Results' : 'Next Question'}
              <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}